name: Deploy to Fly
on:
  workflow_dispatch:
    inputs:
      tag:
        description: image tag to deploy
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          args: "deploy --image ghcr.io/rileymichael/resolvr.io:${{ github.event.inputs.tag }}"